"""Document export functions — PDF, DOCX, PPTX, XLSX, Markdown."""

import os
import uuid

from fundfy.config import settings

# Brand colors
BRAND_PINK = (255, 107, 107)  # #FF6B6B
BRAND_PURPLE = (139, 92, 246)  # #8B5CF6


def _ensure_dir() -> str:
    """Ensure the generated files directory exists and return its path."""
    dir_path = settings.generated_files_dir
    os.makedirs(dir_path, exist_ok=True)
    return dir_path


def export_markdown(title: str, content: str) -> str:
    """Export content as a Markdown file. Returns the file path."""
    dir_path = _ensure_dir()
    filename = f"{uuid.uuid4()}.md"
    filepath = os.path.join(dir_path, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"# {title}\n\n{content}")
    return filepath


def export_pdf(title: str, content: str) -> str:
    """Export content as a professional PDF file. Returns the file path."""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.colors import HexColor
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    )

    dir_path = _ensure_dir()
    filename = f"{uuid.uuid4()}.pdf"
    filepath = os.path.join(dir_path, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        leftMargin=inch,
        rightMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )
    styles = getSampleStyleSheet()

    # Custom styles with brand colors
    styles.add(ParagraphStyle(
        "BrandTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        textColor=HexColor("#8B5CF6"),
        spaceAfter=20,
    ))
    styles.add(ParagraphStyle(
        "BrandHeading",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=16,
        textColor=HexColor("#FF6B6B"),
        spaceBefore=20,
        spaceAfter=10,
    ))
    styles.add(ParagraphStyle(
        "BrandHeading2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        textColor=HexColor("#8B5CF6"),
        spaceBefore=14,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "BrandBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=16,
        spaceAfter=8,
    ))

    story = []

    # Title page
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph(title, styles["BrandTitle"]))
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph("Generated by Fundfy.ai", styles["BrandBody"]))
    story.append(PageBreak())

    # Table of contents (section names)
    sections = content.split("\n## ")
    if len(sections) > 1:
        story.append(Paragraph("Table of Contents", styles["BrandHeading"]))
        story.append(Spacer(1, 12))
        for i, section in enumerate(sections[1:], 1):
            section_title = section.split("\n", 1)[0].strip()
            story.append(Paragraph(f"{i}. {section_title}", styles["BrandBody"]))
        story.append(PageBreak())

    # Content
    for paragraph in content.split("\n"):
        paragraph = paragraph.strip()
        if not paragraph:
            story.append(Spacer(1, 6))
            continue
        # Escape XML special chars for reportlab
        safe_para = paragraph.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        if paragraph.startswith("## "):
            story.append(Paragraph(safe_para[3:], styles["BrandHeading"]))
        elif paragraph.startswith("### "):
            story.append(Paragraph(safe_para[4:], styles["BrandHeading2"]))
        elif paragraph.startswith("# "):
            story.append(Paragraph(safe_para[2:], styles["BrandTitle"]))
        elif paragraph.startswith("- ") or paragraph.startswith("* "):
            story.append(Paragraph(f"\u2022 {safe_para[2:]}", styles["BrandBody"]))
        else:
            story.append(Paragraph(safe_para, styles["BrandBody"]))

    # Page numbers via onPage
    def _add_page_number(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 9)
        canvas.setFillColor(HexColor("#8B5CF6"))
        canvas.drawRightString(
            letter[0] - inch, 0.5 * inch,
            f"Page {doc.page}"
        )
        canvas.drawString(inch, 0.5 * inch, "Fundfy.ai")
        canvas.restoreState()

    doc.build(story, onFirstPage=_add_page_number, onLaterPages=_add_page_number)
    return filepath


def export_business_plan_pdf(title: str, content: str) -> str:
    """Export a professional business plan PDF with TOC, headers, and branding."""
    return export_pdf(title, content)


def export_docx(title: str, content: str) -> str:
    """Export content as a DOCX file using python-docx. Returns the file path."""
    from docx import Document

    dir_path = _ensure_dir()
    filename = f"{uuid.uuid4()}.docx"
    filepath = os.path.join(dir_path, filename)

    doc = Document()
    doc.add_heading(title, 0)

    for paragraph in content.split("\n"):
        paragraph = paragraph.strip()
        if paragraph:
            if paragraph.startswith("## "):
                doc.add_heading(paragraph[3:], level=2)
            elif paragraph.startswith("### "):
                doc.add_heading(paragraph[4:], level=3)
            elif paragraph.startswith("# "):
                doc.add_heading(paragraph[2:], level=1)
            elif paragraph.startswith("- ") or paragraph.startswith("* "):
                doc.add_paragraph(paragraph[2:], style="List Bullet")
            else:
                doc.add_paragraph(paragraph)

    doc.save(filepath)
    return filepath


def export_pptx(title: str, content: str) -> str:
    """Export content as a professional PPTX pitch deck. Splits by ## headings into slides."""
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    dir_path = _ensure_dir()
    filename = f"{uuid.uuid4()}.pptx"
    filepath = os.path.join(dir_path, filename)

    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title_shape = slide.shapes.title
    title_shape.text = title
    title_shape.text_frame.paragraphs[0].font.size = Pt(36)
    title_shape.text_frame.paragraphs[0].font.bold = True
    title_shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(*BRAND_PURPLE)

    # Set subtitle
    if slide.placeholders[1]:
        slide.placeholders[1].text = "Powered by Fundfy.ai"

    # Split content by ## headings into slides
    sections = content.split("## ")
    slide_number = 1
    for section in sections:
        section = section.strip()
        if not section:
            continue

        lines = section.split("\n", 1)
        slide_title = lines[0].strip()
        slide_body = lines[1].strip() if len(lines) > 1 else ""

        slide_layout = prs.slide_layouts[1]  # Title + Content
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = slide_title
        slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(28)
        slide.shapes.title.text_frame.paragraphs[0].font.color.rgb = RGBColor(*BRAND_PINK)

        if slide_body and slide.placeholders[1]:
            tf = slide.placeholders[1].text_frame
            tf.clear()
            for i, bullet in enumerate(slide_body.split("\n")):
                bullet = bullet.strip()
                if not bullet:
                    continue
                if bullet.startswith("- ") or bullet.startswith("* "):
                    bullet = bullet[2:]
                para = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
                para.text = bullet
                para.font.size = Pt(16)
                para.space_after = Pt(8)

        slide_number += 1

    # Thank you slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Thank You"
    slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(36)
    slide.shapes.title.text_frame.paragraphs[0].font.color.rgb = RGBColor(*BRAND_PURPLE)
    if slide.placeholders[1]:
        slide.placeholders[1].text = "Questions?"

    prs.save(filepath)
    return filepath


def export_pitch_deck_pptx(title: str, content: str, brand_colors: tuple | None = None) -> str:
    """Export a professional pitch deck PPTX. Alias for export_pptx with branding."""
    return export_pptx(title, content)


def export_financial_model_xlsx(title: str, data: dict | str) -> str:
    """Export a professional financial model Excel workbook.

    Args:
        title: The workbook title.
        data: Either a dict with sheet data or a string content to parse.

    Returns:
        File path of the generated .xlsx file.
    """
    import json
    from openpyxl import Workbook
    from openpyxl.chart import BarChart, LineChart, Reference
    from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
    from openpyxl.utils import get_column_letter

    dir_path = _ensure_dir()
    filename = f"{uuid.uuid4()}.xlsx"
    filepath = os.path.join(dir_path, filename)

    wb = Workbook()

    # Style definitions
    header_font = Font(bold=True, size=12, color="8B5CF6")
    header_fill = PatternFill(start_color="F3E8FF", end_color="F3E8FF", fill_type="solid")
    border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin"),
    )
    currency_format = '#,##0'
    pct_format = '0.0%'

    # Parse data if string
    if isinstance(data, str):
        try:
            data = json.loads(data)
        except (json.JSONDecodeError, TypeError):
            # Treat as plain content — generate a basic model
            data = _generate_default_financial_data(data)

    if not isinstance(data, dict):
        data = _generate_default_financial_data("")

    # Summary sheet
    ws = wb.active
    ws.title = "Summary"
    ws.append([title])
    ws["A1"].font = Font(bold=True, size=16, color="8B5CF6")
    ws.append([])
    ws.append(["Financial Model Summary"])
    ws["A3"].font = Font(bold=True, size=14)
    ws.append([])

    summary = data.get("summary", {"Total Revenue Year 1": 500000, "Total Revenue Year 3": 2500000, "Break-even Month": 18})
    for key, value in summary.items():
        ws.append([key, value])

    # Revenue Projections sheet
    ws_rev = wb.create_sheet("Revenue Projections")
    months = data.get("months", list(range(1, 13)))
    revenue = data.get("revenue", [i * 50000 for i in range(1, 13)])

    ws_rev.append(["Month", "Revenue", "Cumulative"])
    for cell in ws_rev[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.border = border

    cumulative = 0
    for i, (month, rev) in enumerate(zip(months, revenue), start=2):
        cumulative += rev
        ws_rev.append([month, rev, cumulative])
        ws_rev.cell(row=i, column=2).number_format = currency_format
        ws_rev.cell(row=i, column=3).number_format = currency_format
        # Add formula for cumulative
        if i > 2:
            ws_rev.cell(row=i, column=3).value = f"=C{i-1}+B{i}"

    # Revenue bar chart
    if len(revenue) > 1:
        chart = BarChart()
        chart.title = "Monthly Revenue"
        chart.y_axis.title = "Revenue ($)"
        chart.x_axis.title = "Month"
        data_ref = Reference(ws_rev, min_col=2, min_row=1, max_row=len(revenue) + 1)
        cats = Reference(ws_rev, min_col=1, min_row=2, max_row=len(revenue) + 1)
        chart.add_data(data_ref, titles_from_data=True)
        chart.set_categories(cats)
        ws_rev.add_chart(chart, "E2")

    # Cost Structure sheet
    ws_cost = wb.create_sheet("Cost Structure")
    costs = data.get("costs", {"Engineering": 200000, "Marketing": 100000, "Operations": 80000, "G&A": 50000})
    ws_cost.append(["Category", "Annual Cost"])
    for cell in ws_cost[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.border = border
    for category, cost in costs.items():
        ws_cost.append([category, cost])

    # P&L sheet
    ws_pl = wb.create_sheet("P&L")
    ws_pl.append(["Item", "Year 1", "Year 2", "Year 3"])
    for cell in ws_pl[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.border = border

    pl_data = data.get("pl", {
        "Revenue": [500000, 1500000, 2500000],
        "COGS": [100000, 300000, 500000],
        "Gross Profit": [400000, 1200000, 2000000],
        "Operating Expenses": [430000, 600000, 800000],
        "Net Income": [-30000, 600000, 1200000],
    })
    for item, values in pl_data.items():
        row = [item] + values
        ws_pl.append(row)

    # Cash Flow sheet
    ws_cf = wb.create_sheet("Cash Flow")
    ws_cf.append(["Month", "Cash Flow", "Cumulative Cash"])
    for cell in ws_cf[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.border = border

    cash_flow = data.get("cash_flow", [i * 20000 - 100000 for i in range(1, 13)])
    cumulative_cash = 0
    for i, (month, cf) in enumerate(zip(months, cash_flow), start=2):
        cumulative_cash += cf
        ws_cf.append([month, cf, cumulative_cash])

    # Cash flow line chart
    if len(cash_flow) > 1:
        chart = LineChart()
        chart.title = "Cash Flow"
        chart.y_axis.title = "Amount ($)"
        chart.x_axis.title = "Month"
        data_ref = Reference(ws_cf, min_col=3, min_row=1, max_row=len(cash_flow) + 1)
        cats = Reference(ws_cf, min_col=1, min_row=2, max_row=len(cash_flow) + 1)
        chart.add_data(data_ref, titles_from_data=True)
        chart.set_categories(cats)
        ws_cf.add_chart(chart, "E2")

    # Assumptions sheet
    ws_assumptions = wb.create_sheet("Assumptions")
    ws_assumptions.append(["Assumption", "Value"])
    for cell in ws_assumptions[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.border = border

    assumptions = data.get("assumptions", {
        "Monthly Growth Rate": "15%",
        "Customer Acquisition Cost": "$50",
        "Average Revenue Per User": "$100/mo",
        "Churn Rate": "5%",
        "Gross Margin": "80%",
    })
    for assumption, value in assumptions.items():
        ws_assumptions.append([assumption, value])

    # Auto-size columns
    for ws_sheet in wb.worksheets:
        for col in ws_sheet.columns:
            max_length = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                try:
                    if cell.value:
                        max_length = max(max_length, len(str(cell.value)))
                except Exception:
                    pass
            ws_sheet.column_dimensions[col_letter].width = min(max_length + 2, 30)

    wb.save(filepath)
    return filepath


def _generate_default_financial_data(content: str) -> dict:
    """Generate default financial model data when content is a string."""
    return {
        "summary": {
            "Total Revenue Year 1": 500000,
            "Total Revenue Year 3": 2500000,
            "Break-even Month": 18,
            "Total Funding Needed": 1000000,
        },
        "months": list(range(1, 13)),
        "revenue": [20000, 35000, 45000, 55000, 70000, 85000, 100000, 115000, 130000, 150000, 170000, 200000],
        "costs": {
            "Engineering": 200000,
            "Marketing": 100000,
            "Sales": 80000,
            "Operations": 50000,
            "G&A": 40000,
        },
        "pl": {
            "Revenue": [500000, 1500000, 2500000],
            "COGS": [100000, 300000, 500000],
            "Gross Profit": [400000, 1200000, 2000000],
            "Operating Expenses": [470000, 650000, 850000],
            "Net Income": [-70000, 550000, 1150000],
        },
        "cash_flow": [-80000, -60000, -40000, -20000, 0, 20000, 40000, 60000, 80000, 100000, 120000, 150000],
        "assumptions": {
            "Monthly Growth Rate": "15%",
            "Customer Acquisition Cost": "$50",
            "Average Revenue Per User": "$100/mo",
            "Churn Rate": "5%",
            "Gross Margin": "80%",
        },
    }
